parameters:
  - name: env
    type: string
  - name: svc
    type: string

stages:
- stage: Build_Stage
  displayName: ${{ parameters.env }}_Build_Stage
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.Repository.LocalPath)/'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'TerraformCode'
        publishLocation: 'Container'
